modLoader="javafml"
loaderVersion="[44,)"
license="Obscuria Lithium (c) 2023, All Rights Reserved."

[[mods]]
modId="aquamirae"
version="5.api10"
displayName="Aquamirae"
credits="Krossy, The Exiled Fellow and everyone who supports us on Patreon!"
displayURL="https://www.curseforge.com/members/obscuriaofficial/projects"
logoFile="logo.png"
authors="Obscuria, Pluvia"
description='''
Ship graveyard with terrible deep sea creatures
'''

[[dependencies.aquamirae]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.aquamirae]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3]"
    ordering="NONE"
    side="BOTH"

[[dependencies.aquamirae]]
    modId="obscure_api"
    mandatory=true
    versionRange="[10,]"
    ordering="NONE"
    side="BOTH"

