modLoader="javafml"
loaderVersion="[43,)"
license="Obscuria Lithium (c) 2023, All Rights Reserved."

[[mods]]
    modId="aquamirae"
    version="6.API15"
    displayName="Aquamirae"
    credits="Krossy and everyone who supports us on Patreon!"
    updateJSONURL="https://raw.githubusercontent.com/ObscuriaLithium/Home/main/aquamirae/versions.json"
    issueTrackerURL="https://discord.gg/By29HCKgPx"
    logoFile="logo.png"
    authors="Obscuria, Pluvia"
    description="   Ship graveyard with terrible deep sea creatures."

[[dependencies.aquamirae]]
    modId="obscure_api"
    mandatory=true
    versionRange="[15,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.aquamirae]]
    modId="forge"
    mandatory=true
    versionRange="[43.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.aquamirae]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"

